services:
  backend:
    build:
      context: ./backend
      target: dev
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      target: dev
    env_file: "./frontend/.env"
    ports: ["5173:5173"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
